### ISSUE TITLE
fzy-vim unusable on Vim 7.4.430

### ISSUE THREAD

**Issue by jarednorman** [Dkendal/fzy-vim#1]
I just upgraded my vim and now I can't backspace and fzy is unusably slow when called from Vim.

**Comment by jarednorman** [comment]
@Dkendal why haven't you answered yet

**Comment by jarednorman** [comment]
Come on it's the first day of school, you aren't doing anything anyway.

**Comment by jarednorman** [comment]
_bump_

**Comment by jarednorman** [comment]
FYI downgraded to 7.4.335 and it works fine.

**Comment by Dkendal** [comment]
sorrrry, been busy. I'll take a look tonight

**Comment by jarednorman** [comment]
Still broken. Vim sucks. Switched to Emacs.
